import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Link from 'next/link'
import {usePathname} from 'next/navigation'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const pathname = usePathname();//проверка на ссылку в адрессной строке
  //в хедере проверка - если путь не равен главной странице, то рендерим ссылку на неё в лого

  return (
    <html lang="en">
      <header>
        {pathname !== '/' && <Link href='/'>Main</Link>}
      </header>
      <body className={inter.className}>{children}</body>
    </html>
  )
}
